config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
    get 'homes/dashborad'

    devise_for :users, controllers: { sessions: :sessions }
    resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :orders do
      collection do
          post 'import'
          get 'baidu_map'
          get 'dispatch_list'
          get 'finished_list'
          get 'current'
          get 'waiting'
      end
    end

  # get '/orders/dispatch/:id', to: 'orders#dispatch'
  # resources :items
  resources :teams

  resource :user, only: [:edit] do
    collection do
        patch 'update_password'
    end
  end

  root 'homes#dashboard'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :team

  def imported_orders
    @imported_orders ||= load_imported_orders
  end

  def load_imported_orders
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(1)
    header2column = ["id", "info_no", "lading_no", "create_time", "customer", "area_code", "phone", "province", "city",
                     "county", "street", "address", "category", "count", "uncount", "purchase_date", "customer_attribute",
                     "sale_type", "sale_no", "sale_name", "expected_time", "create_network_no", "create_network",
                     "service_date", "service_network_no", "service_network", "status", "note", "other_note",
                     "finished_time", "item_type", "item_count", "item_price", "item_type2", "item_count2", "item_price2",
                     "item_type3", "item_count3", "item_price3"]
    (3..spreadsheet.last_row).map do |i|
      row = Hash[header2column, spreadsheet.row(i).transpose]

      order = Order.find_by(lading_no: row["id"]) || Order.new
      # order = Order.new
      if row["street"]
        order.install_date = row["streeat"].to_date
      else
        order.install_date = Date.tomorrow
      end
      order.attributes = row.to_hash.slice(*row.to_hash.keys)
      order.lng = BaiduMap.geocoder(address: row["address"])["result"]["location"]["lng"]
      order.lat = BaiduMap.geocoder(address: row["address"])["result"]["location"]["lat"]
      order.save!
    end
  end

  def open_spreadsheet
    case File.extname(file.original_filename)
      when  ".csv" then Csv.new(file.path, nil, :ignore)
      when  ".xls" then Excel.new(file.path)
      when  ".xlsx" then Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.like(status, like)
    Order.where("status=? lading_no LIKE ? OR customer LIKE ? OR item_type LIKE ? OR sale_name LIKE ? OR address LIKE ? OR phone ? OR note LIKE ?",
                status, "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%")
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    # header = spreadsheet.row(1)
    header2column = ["id", "info_no", "lading_no", "create_time", "customer", "area_code", "phone", "province", "city",
                     "county", "street", "address", "category", "count", "uncount", "purchase_date", "customer_attribute",
                     "sale_type", "sale_no", "sale_name", "expected_time", "create_network_no", "create_network",
                     "service_date", "service_network_no", "service_network", "status", "note", "other_note",
                     "finished_time", "item_type", "item_count", "item_price", "item_type2", "item_count2", "item_price2",
                     "item_type3", "item_count3", "item_price3"]
    (3..spreadsheet.last_row).map do |i|
      row = Hash[[header2column, spreadsheet.row(i)].transpose]
      puts "row ID: "
      puts row["id"]
      if (row["id"] != nil)
        unless Order.find_by(lading_no: row["lading_no"])
          order = Order.new
          order.attributes = row.to_hash.slice(*row.to_hash.keys)

          if Order.last.nil?
            order.id = row["id"].to_i
          else
            order.id = Order.last.id + 1
          end

          order.info_no = row["info_no"].to_s
          order.lading_no = row["lading_no"].is_a?(Numeric) ? row["lading_no"].to_i.to_s : row["lading_no"]
          order.customer= row["customer"].to_s
          order.phone = row["phone"].is_a?(Numeric) ? row["phone"].to_i.to_s : row["phone"]
          order.area_code=row["area_code"].to_s
          order.province=row["province"].to_s
          order.city=row["city"].to_s
          order.county=row["county"].to_s
          order.street=row["street"].to_s
          order.address=row["address"].to_s
          order.note=row["note"].to_s
          order.item_type=row["item_type"].to_s
          order.lng = BaiduMap.geocoder(address: row["address"])["result"]["location"]["lng"]
          order.lat = BaiduMap.geocoder(address: row["address"])["result"]["location"]["lat"]
          order.install_date = row["street"]
          order.save!
        end
      else
        puts "########"
        puts "Error data ID is nil"
      end
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when  ".csv" then Roo::Csv.new(file.path, nil, :ignore)
      when  ".xls" then Roo::Excel.new(file.path)
      when  ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.dispatch
    Order.where("status = '网点已派工'")
  end

  def self.to_csv(options = {})
    CSV.generate(orders) do |csv|
      csv << column_names
      all.each do |order|
        csv << order.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout "order"
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    if params["like"]
      like = params["like"]
    else
      like = ""
    end

    @orders = Order.where("lading_no LIKE ? OR customer LIKE ? OR item_type LIKE ? OR sale_name LIKE ? OR team_name LIKE ?
                           OR address LIKE ? OR phone LIKE ? OR note LIKE ?", "%#{like}%", "%#{like}%", "%#{like}%",
                          "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%")
                  .order(install_date: :desc).page params[:page]

    @all = Order.all.count
    @undispatch_all = Order.where("status = '待网点派工'").count
    @dispatching_all = Order.where("install_date='#{Date.tomorrow}'").count
    @dispatched_all = Order.where("status='网点已派工'").count
    @finished_all = Order.where("status='派工已完工'").count

    respond_to :html, :json

  end

  def waiting
    if params["like"]
      like = params["like"]
    else
      like = ""
    end

    @orders = Order.where("lading_no LIKE ? OR customer LIKE ? OR item_type LIKE ? OR sale_name LIKE ? OR team_name LIKE ?
                         OR address LIKE ? OR phone LIKE ? OR note LIKE ?", "%#{like}%", "%#{like}%", "%#{like}%",
                          "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%")
                  .where("status = '待网点派工'")
                  .order(:phone, :address).page params[:page]

    @all = Order.all.count
    @undispatch_all = Order.where("status = '待网点派工'").count
    @dispatching_all = Order.where("install_date='#{Date.tomorrow}'").count
    @dispatched_all = Order.where("status='网点已派工'").count
    @finished_all = Order.where("status='派工已完工'").count

    respond_to :html, :json

  end

  # POST /orders/import
  def import
    Order.import(params[:file])
    redirect_to orders_url, notice: 'Order was successfully created.'
  end

  # GET /orders/baidu_map
  def baidu_map
    # @orders = Order.order(address: :asc)

    @orders = Order.where(install_date: Date.tomorrow).order(lng: :asc)
    @teams = Team.order(name: :asc)

    @all = Order.all.count
    @undispatch_all = Order.where("status='待网点派工'").count
    @current_all = Order.where(install_date: Date.today).count
    @dispatched_all = Order.where("status='网点已派工'").count
    @dispatching_all = @orders.count
    @finished_all = Order.where("status='派工已完工'").count
    bom = Date.today.beginning_of_month
    eom = Date.today.end_of_month
    @counts = {}
    @teams.each do |t|
      last_install = Order.where("team_name = ?", t.name).last
      last_date = last_install ? last_install.install_date : bom
      daley = (Date.today - last_date)
      team_count = Order.where("team_name = ?", t.name).where("status='网点已派工'").where("install_date <= ? and install_date >= ?", eom, bom).count
      @counts["#{t.name}"] = "#{team_count}/#{daley}"
    end

    respond_to :html, :json

    render layout: "ordersemantic"

    # render layout: "order"
  end

  def current
    @orders = Order.where(install_date: Date.today).where("status='网点已派工' OR status='待网点派工'").order(lng: :asc)
    @teams = Team.order(name: :asc)

    @all = Order.all.count
    @undispatch_all = Order.where("status='待网点派工'").count
    @dispatched_all = Order.where("status='网点已派工'").count
    @dispatching_all = Order.where(install_date: Date.tomorrow).count
    @current_all = @orders.count
    @finished_all = Order.where("status='派工已完工'").count
    bom = Date.today.beginning_of_month
    eom = Date.today.end_of_month
    @counts = {}
    @teams.each do |t|
      last_install = Order.where("team_name = ?", t.name).last
      last_date = last_install ? last_install.install_date : bom
      daley = (Date.today - last_date)
      team_count = Order.where("team_name = ?", t.name).where("status='网点已派工'").where("install_date <= ? and install_date >= ?", eom, bom).count
      @counts["#{t.name}"] = "#{team_count}/#{daley}"
    end

    respond_to :html, :json, :xls

    render layout: "ordersemantic"

    # render layout: "order"
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_all = Order.all.count
    @dispatch_all = Order.where("status='网点已派工'").count
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  def dispatch_list
    # @orders = Order.where("status = '网点已派工'").order(team_name: :asc).page params[:page]
    @all = Order.all.count
    @undispatch_all = Order.where("status='待网点派工'").count
    @dispatched_all = Order.where("status='网点已派工'").count
    @dispatching_all = Order.where(install_date: Date.tomorrow).count
    @current_all = Order.where(install_date: Date.today).count
    @finished_all = Order.where("status='派工已完工'").count

    if params["like"]
      like = params["like"]
    else
      like = ""
    end

    unless params["install_date"].blank?
     ins_date = params["install_date"].to_date
    else
     ins_date = Date.tomorrow
    end

    @orders = Order.where("lading_no LIKE ? OR customer LIKE ? OR item_type LIKE ? OR sale_name LIKE ? OR team_name LIKE ?
                           OR address LIKE ? OR phone LIKE ? OR note LIKE ?", "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%",
                          "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%")
                  .where("status = '网点已派工'").where(install_date: ins_date)
                  .order(:team_name, :phone)
                  #.order(team_name: :asc).page params[:page]

    respond_to :html, :json, :xls

    render layout: "print"
  end

  def finished_list
    if params["like"]
      like = params["like"]
    else
      like = ""
    end

    @orders = Order.where("lading_no LIKE ? OR customer LIKE ? OR item_type LIKE ? OR sale_name LIKE ?
                           OR address LIKE ? OR phone LIKE ? OR note LIKE ?", "%#{like}%", "%#{like}%", "%#{like}%",
                          "%#{like}%", "%#{like}%", "%#{like}%", "%#{like}%").where("status = '派工已完工'").order(install_date: :asc).page params[:page]

    # @orders = Order.where("status = '派工已完工'").order(:install_date)
    @all = Order.all.count
    @undispatch_all = Order.where("status='待网点派工'").count
    @dispatching_all = Order.where("install_date='#{Date.tomorrow}'").count
    @dispatched_all = Order.where("status='派工已派工'").count
    @finished_all = @orders.count
    respond_to :html, :json, :xls

    # render layout: "ordersemantic"
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      @order.lng = BaiduMap.geocoder(address: params[:order]["address"])["result"]["location"]["lng"]
      @order.lat = BaiduMap.geocoder(address: params[:order]["address"])["result"]["location"]["lat"]
      @order.status="待网点派工"
      if Order.last
        @order.id = Order.last.id + 1
      end
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update

    unless params["order"]
      if (params["name"] && params["value"])
        params["order"] = { "#{params['name']}":params['value']  }
      end
    end
    #update address auto updating lng&lat
    if params['name'] == 'address'
      params['order']['lng'] = BaiduMap.geocoder(address: params['value'])['address']['result']['location']['lng']
      params['order']['lat'] = BaiduMap.geocoder(address: params['value'])['address']['result']['location']['lat']
    else
      params['order']['lng'] = BaiduMap.geocoder(address: params['order']['address'])['address']['result']['location']['lng']
      params['order']['lat'] = BaiduMap.geocoder(address: params['order']['address'])['address']['result']['location']['lat']
    end

    respond_to do |format|

      if @order.update(order_params)

        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params

    params.require(:order).permit(:id, :info_no, :lading_no, :create_time, :customer, :area_code, :phone, :province, :city,
                                  :county, :street, :address, :category, :count, :uncount, :purchase_date, :customer_attribute,
                                  :sale_type, :sale_no, :sale_name, :expected_time, :create_network_no, :create_network,
                                  :service_date, :service_network_no, :service_network, :status, :note, :other_note,
                                  :finished_time, :item_type, :item_count, :item_price, :item_type2, :item_count2, :item_price2,
                                  :item_type3, :item_count3, :item_price3, :team_name, :install_date, :operator, :dispatch_time,

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
    <div class="form-group">
      <% if order.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

            <ul>
              <% order.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :lading_no %>
        <%= f.text_field :lading_no, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :customer %>
        <%= f.text_field :customer, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :sale_name %>
        <%= f.text_field :sale_name, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :item_type %>
        <%= f.text_field :item_type, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :install_date %>
        <%= f.date_field :install_date, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :team_name %>
        <%= f.text_field :team_name, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :note %>
        <%= f.text_field :note, class: "form-control" %>
      </div>

      <div class="btn btn-default">
        <%= f.submit %>
      </div>

    </div>
<% end %>

app/views/orders/dispatch.html.erb
<table class="ui selectable celled table">
  <thead>
  <tr>
    <th>提货单号</th>
    <th class="single line">客户姓名</th>
    <th>客户地址</th>
    <th>联系电话</th>
    <th>客户要求</th>
    <th>商品名称</th>
    <th>销售单位</th>
    <th>创建时间</th>
    <th class="single line">安装工</th>
    <th class="single line">派工状态</th>
  </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @order.lading_no %></td>
        <td><%= @order.customer %></td>
        <td><%= @order.address %></td>
        <td><%= @order.phone %></td>
        <td><%= @order.note %></td>
        <td><%= @order.item_type %></td>
        <td><%= @order.sale_name %></td>
        <td><%= @order.create_time %></td>
        <td><%= @order.team_name %></td>
        <td><%= @order.status %></td>
      </tr>
  </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/finished_list.html.erb
<%= form_tag "/orders/finished_list", method: "get" do %>
    <div class="row" style="margin-bottom: 10px;">
      <div class="col-lg-2">
        <div class="input-group">
          <%= search_field_tag "like", nil, class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "搜", class: "btn btn-default" %>
          </span>
        </div>
      </div>
    </div>
<% end %>

<table id="orders"
       data-toggle="table"
       data-detail-view="true"
       data-detail-formatter="detailFormatter"
       data-minimum-count-columns="2"
       data-id-field="id">
  <thead>
  <tr>
    <th>销售单号</th>
    <th class="single line">客户姓名</th>
    <th>客户地址</th>
    <th>联系电话</th>
    <th>商品型号</th>
    <th>销售单位</th>
    <th class="single line">安装时间</th>
    <th class="single line">安装工</th>
    <th>派工状态</th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.lading_no %></td>
        <td><%= order.customer %></td>
        <td><%= order.address %></td>
        <td><%= order.phone %></td>
        <td><%= order.item_type %></td>
        <td><%= order.sale_name %></td>
        <td><%= order.install_date %></td>
        <td><%= order.team_name %></td>
        <td><%= order.status %></td>
        <!--<td><%#= link_to '查看', order %></td>-->
        <!--<td><%#= link_to '编辑', edit_order_path(order) %></td>-->
        <!--<td><%#= link_to '删除', order, method: :delete, data: { confirm: '确定要删除么?' } %></td>-->
      </tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="11">
        <div class="ui right floated pagination menu">
          <%= paginate @orders %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>

<script>
//    $(document).ready(function () {
//        $('#orders').DataTable();
//    });
</script>

app/views/orders/index.html.erb
<%= form_tag "/orders", method: "get" do %>
    <div class="row col-md-8" style="margin-bottom: 10px;">
      <div class="col-lg-6">
        <div class="input-group">
          <%= search_field_tag "like", nil, class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "查询", class: "btn btn-default" %>
          </span>
        </div>
      </div>
    </div>
<% end %>
<div class="col-md-4">
  <%= link_to "新建工单", new_order_path, class: "btn btn-primary pull-right" %>
</div>

<table id="orders"
       data-toggle="table"
       data-detail-view="true"
       data-detail-formatter="detailFormatter"
       data-minimum-count-columns="2"
       data-id-field="id">
  <thead>
    <tr>
      <th>ID</th>
      <th>安装工</th>
      <th>客户姓名</th>
      <th>联系电话</th>
      <th>客户地址</th>
      <th class="col-sm-1">安装时间</th>
      <!--<th class="single line">安装工</th>-->
      <th>备注</th>
      <th>销售单位</th>
      <th>商品型号</th>
      <th>销售单号</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td class="teams">
          <a href="#" data-name="team" data-type="text" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.team_name %>"
             class="team-click"><%= order.team_name %>
          </a>
        </td>
        <td>
          <a href="#" data-name="customer" data-type="text" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.customer %>"
             class="customer-click"><%= order.customer %>
          </a>
        </td>
        <td>
          <a href="#" data-name="phone" data-type="text" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.phone %>"
             class="phone-click"><%= order.phone %>
          </a>
        </td>
        <td>
          <a href="#" data-name="address" data-type="textarea" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.address %>"
             class="address-click"><%= order.address %>
          </a>
        </td>
        <td>
          <a href="#" data-name="install_date" data-type="date" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.install_date %>"
             class="install_date-click"><%= order.install_date %>
          </a>
        </td>
        <!--<td><%#= order.team_name %></td>-->
        <td>
          <a href="#" data-name="note" data-type="textarea" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.note %>"
             class="note-click"><%= order.note %>
          </a>
        </td>
        <td><%= order.sale_name %></td>
        <td>
          <a href="#" data-name="item_type" data-type="text" data-pk="<%= order.id %>"
             data-url="/orders/<%= order.id.to_s + ".json" %>" data-value="<%= order.item_type %>"
             class="install_date-click"><%= order.item_type %>
          </a></td>
        <td><%= order.lading_no %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="11">
        <div class="">
          <%= paginate @orders %>
          <%= page_entries_info @orders %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>

<div class="modal hide fade in" id="new-order">
  <div class="modal-header">
    <a class="close" data-dismiss="modal"></a>
    <h4>新建工单</h4>
  </div>
  <div class="modal-body">

  </div>
</div>

<script>
    $(function () {
//        $.fn.bootstrapTable.defaults;

        $("#orders").on('click-row.bs.table', function (e, row, $element) {
            $('.success').removeClass('success');
            $($element).addClass('success');
        });

        $.fn.editable.defaults.ajaxOptions = {type: "PUT", headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') }};
        $('.team-click').editable({mode: "inline"});
        $('.customer-click').editable();
        $('.phone-click').editable();
        $('.address-click').editable({mode: "inline"});
        $('.install_date-click').editable({
            placement:'bottom',
            clear: false,
            format: 'yyyy/mm/dd',
            viewformat: 'yyyy-mm-dd'
        });
        $('.note-click').editable({mode: "inline"});

        function detailFormatter(index, row) {
            var html = [];
            $.each(row, function (key, value) {
                console.log(key);
                html.push('<p><b>' + key + ':</b> ' + value + '</p>');
            });
            return html.join('');
        }

        $('#new-order').modal({
          show: false
        });
        $('#dispatch').modal({
          show: false
        })
    });
</script>

app/views/orders/new.html.erb
<h1>新建工单</h1>

<%= render 'form', order: @order %>

<%= link_to '返回', orders_path %>

app/views/orders/show.html.erb
<h4 class="ui horizontal divider header"><i class="tag icon"></i>工单信息</h4>
<table class="ui definition table">
  <tbody>
  <tr>
    <td>提货单号/销售单号</td>
    <td><%= @order.lading_no %></td>
    <td class="active">商品型号</td>
    <td><%= @order.item_type %></td>
  </tr>
  <tr>
    <td>销售部门</td>
    <td><%= @order.sale_name %></td>
    <td class="active">创建时间</td>
    <td><%= @order.create_time %></td>
  </tr>
  <tr>
    <td>创建网点</td>
    <td><%= @order.create_network %></td>
    <td class="active">服务网点</td>
    <td><%= @order.service_network %></td>
  </tr>
  <tr>
    <td>工单状态</td>
    <td><%= @order.status %></td>
    <td class="active">安装工</td>
    <td><%= @order.team_name %></td>
  </tr>
  </tbody>
</table>
<h4 class="ui horizontal divider header"><i class="user icon"></i>客户信息 </h4>
<table class="ui definition table">
  <tbody>
  <tr>
    <td>客户姓名</td>
    <td><%= @order.customer %></td>
  </tr>
  <tr>
    <td>联系电话</td>
    <td><%= @order.phone %></td>
  </tr>
  <tr>
    <td>客户属性</td>
    <td><%= @order.customer_attribute %></td>
  </tr>
  <tr>
    <td>详细地址</td>
    <td><%= @order.address %></td>
  </tr>
  <tr>
    <td>备注</td>
    <td><%= @order.note %></td>
  </tr>
  </tbody>
</table>

<%= link_to '返回', orders_path, class: "ui button" %>