config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
    get 'homes/dashborad'

    devise_for :users, controllers: { sessions: :sessions }
    resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :orders do
      collection do
          post 'import'
          get 'baidu_map'
          get 'dispatch_list'
          get 'finished_list'
          get 'current'
          get 'waiting'
      end
    end

  # get '/orders/dispatch/:id', to: 'orders#dispatch'
  # resources :items
  resources :teams

  resource :user, only: [:edit] do
    collection do
        patch 'update_password'
    end
  end

  root 'homes#dashboard'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh" ng-csp="" ng-app="EluneApp"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Elune Tasks Manager</title>
    <!-- mobile meta -->
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

		<!--[if IE]>
			<link rel="shortcut icon" href="favicon.ico">
		<![endif]-->
		<!-- or, set /favicon.ico for IE10 win -->
		<meta name="msapplication-TileColor" content="#f01d4f">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--[if lt IE 8]>
		    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
    <div class="ui middle aligned center aligned grid" style="height: 100%;">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh" ng-csp="" ng-app="EluneApp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Elune Tasks Manager</title>
  <!-- mobile meta -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

  <!--[if IE]>
  <link rel="shortcut icon" href="favicon.ico">
  <![endif]-->
  <!-- or, set /favicon.ico for IE10 win -->
  <meta name="msapplication-TileColor" content="#f01d4f">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="main-wrapper">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="ui secondary pointing menu">
  <a href="/" class="<%= current_page?('/')? "active" : "" %> item">首页 </a>
  <a href="/orders" class="<%= current_page?('/orders')? "active" : "" %> item">工单管理 </a>
  <a href="/teams" class="<%= current_page?('/teams')? "active" : "" %> item">安装队管理 </a>
  <div class="right menu">
    <% if user_signed_in? %>
        <%= link_to('退出', destroy_user_session_path, :method => :delete, class: "ui item") %>
    <% else %>
        <%= link_to('登录', new_user_session_path, class: "ui item")  %>
    <% end %>
  </div>
</div>
<div class="ui bottom attached grid pushable">
  <!-- Main view for templates -->
    <%= yield %>
</div>
</body>
</html>

app/views/layouts/item.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh" ng-csp="" ng-app="EluneApp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Elune Tasks Manager</title>
  <!-- mobile meta -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="renderer" content="webkit">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!--[if IE]>
  <link rel="shortcut icon" href="favicon.ico">
  <![endif]-->
  <!-- or, set /favicon.ico for IE10 win -->
  <meta name="msapplication-TileColor" content="#f01d4f">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="main-wrapper">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="ui secondary pointing menu">
  <a href="/" class="<%= current_page?('/')? "active" : "" %> item">首页 </a>
  <a href="/orders" class="<%= current_page?('/orders')? "active" : "" %> item">工单管理 </a>
  <a href="/teams" class="<%= current_page?('/teams')? "active" : "" %> item">安装队管理 </a>
  <div class="right menu">
    <% if user_signed_in? %>
        <%= link_to('退出', destroy_user_session_path, :method => :delete, class: "ui item") %>
    <% else %>
        <%= link_to('登录', new_user_session_path, class: "ui item")  %>
    <% end %>
  </div>
</div>
<div class="ui bottom attached grid pushable">
  <!--<div class="ui grid">-->
  <div class="three wide column">
    <!-- Sidebar -->
    <div class="ui vertical menu">
      <a class="item <%= current_page?('/items')? " teal active" : "" %>" href="/items">
        库存列表
        <div class="ui label <%= current_page?('/items')? " teal left pointing" : "" %>">1</div>
      </a>
    </div>
  </div>
  <!-- Main view for templates -->
  <div data-ng-view="" class="thirteen wide stretched column">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/order.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh" ng-csp="" ng-app="EluneApp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>诚信工单管理</title>
  <!-- mobile meta -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="renderer" content="webkit">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!--[if IE]>
  <link rel="shortcut icon" href="favicon.ico">
  <![endif]-->
  <!-- or, set /favicon.ico for IE10 win -->
  <meta name="msapplication-TileColor" content="#f01d4f">
  <%= csrf_meta_tags %>

  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.bootcss.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css" rel="stylesheet" >
  <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>

  <script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-zh-CN.min.js"></script>
  <!--<script src="/assets/bootstrap-table-editable.js"></script>-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.zh-CN.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
  <!--<script src="https://cdn.bootcss.com/moment.js/2.18.1/locale/zh-cn.js"></script>-->
  <!--<script src="https://cdn.bootcss.com/moment.js/2.18.1/moment.min.js"></script>-->
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=P76vLiV6EWwzm109FtNDZ7ttbMBR4SOx"></script>

<style type="text/css">
  body {
    overflow: hidden;
  }

  .nav-list {
    top: 50px;
    left: 0;
    width: 400px;
    bottom: 0;
    background-color: rgb(247, 247, 247);
    border-right: 1px solid rgb(221, 221, 221);
    z-index: 91;
    transition: transform 0.2s ease;
    -webkit-transition: transform 0.2s ease;
    -webkit-transform: translate3d(-100%, 0, 0);
    transform: translate3d(-100%, 0, 0);
    position: fixed;
    padding-top: 49px;
  }

  .nav-list.active {
    transform: translate3d(0, 0, 0);
    -webkit-transform: translate3d(0, 0, 0);
  }

  .nav-list .title {
    line-height: 46px;
    font-size: 18px;
    padding-left: 10px;
    text-shadow: rgb(255, 255, 255) 0 1px 0;
    border-bottom: 1px solid rgb(229, 229, 229);
    position: absolute;
    height: 49px;
    top: 0;
    right: 0;
    left: 0;
  }

  a.toggle {
    position: absolute;
    top: 9px;
    right: -49px;
  }

  .nav-list.active a.toggle {
    right: 9px;
  }

  a.toggle .glyphicon-chevron-left,
  .nav-list.active a.toggle .glyphicon-chevron-right {
    display: none;
  }

  a.toggle .glyphicon-chevron-right,
  .nav-list.active a.toggle .glyphicon-chevron-left {
    display: block;
  }

  .nav-list ul {
    height: 100%;
    overflow: auto;
    padding: 10px;
  }

  .navigation {
    position: fixed;
    top: 51px;
    height: 30px;
    text-align: center;
  }

  .navigation .previous,
  .navigation .next {
    display: none;
    margin-left: 15px;
    margin-right: 15px;
    line-height: 30px;
  }

  .ribbon {
    background-color: #a00;
    overflow: hidden;
    white-space: nowrap;
    /* top left corner */
    position: fixed;
    right: -60px;
    top: 90px;
    /* 45 deg ccw rotation */
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    transform: rotate(45deg);
    /* shadow */
    -webkit-box-shadow: 0 0 10px #888;
    -moz-box-shadow: 0 0 10px #888;
    box-shadow: 0 0 10px #888;
    z-index: 999;
  }

  .ribbon a {
    border: 1px solid #faa;
    color: #fff;
    display: block;
    font: bold 81.25% 'Helvetica Neue', Helvetica, Arial, sans-serif;
    margin: 1px 0;
    padding: 10px 50px;
    text-align: center;
    text-decoration: none;
    /* shadow */
    text-shadow: 0 0 5px #444;
  }

  .content {
    position: fixed;
    width: 100%;
    top: 5em;
    bottom: 0;
  }

  .fixed-table-body {
    height: auto;
    min-height: 360px;
  }
</style>
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a href="/" class="<%= current_page?('/')? "active" : "" %> navbar-text">首页 </a>
    <a href="/orders" class="<%= current_page?('/orders')? "active" : "" %> navbar-text">工单管理 </a>
    <a href="/teams" class="<%= current_page?('/teams')? "active" : "" %> navbar-text">安装队管理 </a>
    <div class="right menu">
      <% if user_signed_in? %>
          <%= link_to('退出', destroy_user_session_path, :method => :delete, class: "navbar-text navbar-right") %>
      <% else %>
          <%= link_to('登录', new_user_session_path, class: "navbar-text navbar-text")  %>
      <% end %>
    </div>
  </div>
</nav>
<div class="navigation">
  <div class="container">
    <a class="previous" href="#"></a>
    <a class="next" href="#"></a>
  </div>
</div>
<div class="content">
    <!--<div class="ui grid">-->
    <div class="col-md-2">
      <!-- Sidebar -->
      <div class="list-group">
        <a class="list-group-item <%= current_page?('/orders/waiting')? " active" : "" %>" href="/orders/waiting">
          待派工列表
          <div class="badge"><%= @undispatch_all %></div>
        </a>
        <a class="list-group-item <%= current_page?('/orders/baidu_map')? " active" : "" %>" href="/orders/baidu_map">
          地图派工
          <div class="badge"><%= @dispatching_all %></div>
        </a>
        <a class="list-group-item <%= current_page?('/orders/current')? " active" : "" %>" href="/orders/current">
          现在派工
          <div class="badge"> <%= @current_all %></div>
        </a>
        <a class="list-group-item <%= current_page?('/orders/dispatch_list')? " active" : "" %>" href="/orders/dispatch_list">
          打印列表
          <div class="badge"><%= @dispatched_all %></div>
        </a>
        <a class="list-group-item <%= current_page?('/orders/finished_list')? " active" : "" %>" href="/orders/finished_list">
          已完工列表
          <span class="badge"><%= @finished_all %></span>
        </a>
        <a class="list-group-item <%= current_page?('/orders')? " active" : "" %>" href="/orders">
          所有工单列表
          <span class="badge"><%= @all %></span>
        </a>
      </div>
      <div class="col-md-2">
        <div class="list">
            <%= form_tag import_orders_path, multipart: true, html: {class: "ui form"} do |f| %>
                <% if Order.new.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(Order.new.errors.count, "error") %> prohibited this import from completing:</h2>
                      <ul>
                        <% Order.new.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                <% else %>
                    <%= file_field_tag :file %>
                    <%= submit_tag "导入格力工单", class: "ui mini primary button" %>
                <% end %>
            <% end %>
        </div>
      </div>
    </div>
    <!-- Main view for templates -->
    <div class="col-md-10" style="height: 100%;">
      <%= yield %>
    </div>
</div>
<!--<nav class="navbar navbar-inverse navbar-fixed-bottom"><h5>power by elune.info</h5></nav>-->
<%= yield :body_tail %>
</body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh" ng-csp="" ng-app="EluneApp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>诚信工单管理</title>
  <!-- mobile meta -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="renderer" content="webkit">
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

  <!--[if IE]>
  <link rel="shortcut icon" href="favicon.ico">
  <![endif]-->
  <!-- or, set /favicon.ico for IE10 win -->
  <meta name="msapplication-TileColor" content="#f01d4f">
  <%= csrf_meta_tags %>

  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.bootcss.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css" rel="stylesheet" >
  <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>

  <script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/locale/bootstrap-table-zh-CN.min.js"></script>
  <!--<script src="/assets/bootstrap-table-editable.js"></script>-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.zh-CN.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

  <!--<script src="https://cdn.bootcss.com/moment.js/2.18.1/locale/zh-cn.js"></script>-->
  <!--<script src="https://cdn.bootcss.com/moment.js/2.18.1/moment.min.js"></script>-->

  <style type="text/css">
    body {
      overflow: hidden;
    }

    .nav-list {
      top: 50px;
      left: 0;
      width: 400px;
      bottom: 0;
      background-color: rgb(247, 247, 247);
      border-right: 1px solid rgb(221, 221, 221);
      z-index: 91;
      transition: transform 0.2s ease;
      -webkit-transition: transform 0.2s ease;
      -webkit-transform: translate3d(-100%, 0, 0);
      transform: translate3d(-100%, 0, 0);
      position: fixed;
      padding-top: 49px;
    }

    .nav-list.active {
      transform: translate3d(0, 0, 0);
      -webkit-transform: translate3d(0, 0, 0);
    }

    .nav-list .title {
      line-height: 46px;
      font-size: 18px;
      padding-left: 10px;
      text-shadow: rgb(255, 255, 255) 0 1px 0;
      border-bottom: 1px solid rgb(229, 229, 229);
      position: absolute;
      height: 49px;
      top: 0;
      right: 0;
      left: 0;
    }

    a.toggle {
      position: absolute;
      top: 9px;
      right: -49px;
    }

    .nav-list.active a.toggle {
      right: 9px;
    }

    a.toggle .glyphicon-chevron-left,
    .nav-list.active a.toggle .glyphicon-chevron-right {
      display: none;
    }

    a.toggle .glyphicon-chevron-right,
    .nav-list.active a.toggle .glyphicon-chevron-left {
      display: block;
    }

    .nav-list ul {
      height: 100%;
      overflow: auto;
      padding: 10px;
    }

    .navigation {
      position: fixed;
      top: 51px;
      height: 30px;
      text-align: center;
    }

    .navigation .previous,
    .navigation .next {
      display: none;
      margin-left: 15px;
      margin-right: 15px;
      line-height: 30px;
    }

    .ribbon {
      background-color: #a00;
      overflow: hidden;
      white-space: nowrap;
      /* top left corner */
      position: fixed;
      right: -60px;
      top: 90px;
      /* 45 deg ccw rotation */
      -webkit-transform: rotate(45deg);
      -moz-transform: rotate(45deg);
      -ms-transform: rotate(45deg);
      -o-transform: rotate(45deg);
      transform: rotate(45deg);
      /* shadow */
      -webkit-box-shadow: 0 0 10px #888;
      -moz-box-shadow: 0 0 10px #888;
      box-shadow: 0 0 10px #888;
      z-index: 999;
    }

    .ribbon a {
      border: 1px solid #faa;
      color: #fff;
      display: block;
      font: bold 81.25% 'Helvetica Neue', Helvetica, Arial, sans-serif;
      margin: 1px 0;
      padding: 10px 50px;
      text-align: center;
      text-decoration: none;
      /* shadow */
      text-shadow: 0 0 5px #444;
    }

    .content {
      position: fixed;
      width: 100%;
      top: 5em;
      bottom: 0;
    }

    .fixed-table-body {
      height: auto;
    }
  </style>

</head>

<body class="main-wrapper">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a href="/" class="<%= current_page?('/')? "active" : "" %> navbar-text">首页 </a>
    <a href="/orders" class="<%= current_page?('/orders')? "active" : "" %> navbar-text">工单管理 </a>
    <a href="/teams" class="<%= current_page?('/teams')? "active" : "" %> navbar-text">安装队管理 </a>
    <div class="right menu">
      <% if user_signed_in? %>
          <%= link_to('退出', destroy_user_session_path, :method => :delete, class: "navbar-text navbar-right") %>
      <% else %>
          <%= link_to('登录', new_user_session_path, class: "navbar-text navbar-text")  %>
      <% end %>
    </div>
  </div>
</nav>
<div class="navigation">
  <div class="container">
    <a class="previous" href="#"></a>
    <a class="next" href="#"></a>
  </div>
</div>
<div class="content">
  <!--<div class="ui grid">-->
  <div class="col-md-2">
    <!-- Sidebar -->
    <div class="list-group">
      <a class="list-group-item <%= current_page?('/orders/waiting')? " active" : "" %>" href="/orders/waiting">
        待派工列表
        <div class="badge"><%= @undispatch_all %></div>
      </a>
      <a class="list-group-item <%= current_page?('/orders/baidu_map')? " active" : "" %>" href="/orders/baidu_map">
        地图派工
        <div class="badge"><%= @dispatching_all %></div>
      </a>
      <a class="list-group-item <%= current_page?('/orders/current')? " active" : "" %>" href="/orders/current">
        今天的派工
        <div class="badge"> <%= @current_all %></div>
      </a>
      <a class="list-group-item <%= current_page?('/orders/dispatch_list')? " active" : "" %>" href="/orders/dispatch_list">
        打印列表
        <div class="badge"><%= @dispatched_all %></div>
      </a>
      <a class="list-group-item <%= current_page?('/orders/finished_list')? " active" : "" %>" href="/orders/finished_list">
        已完工列表
        <span class="badge"><%= @finished_all %></span>
      </a>
      <a class="list-group-item <%= current_page?('/orders')? " active" : "" %>" href="/orders">
        所有工单列表
        <span class="badge"><%= @all %></span>
      </a>
    </div>
    <div class="col-md-2">
      <div class="list">
        <%= form_tag import_orders_path, multipart: true, html: {class: "ui form"} do |f| %>
            <% if Order.new.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(Order.new.errors.count, "error") %> prohibited this import from completing:</h2>
                  <ul>
                    <% Order.new.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% else %>
                <%= file_field_tag :file %>
                <%= submit_tag "导入格力工单", class: "ui mini primary button" %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Main view for templates -->
  <div class="col-md-10" style="height: 100%;overflow: auto;">
    <%= yield %>
  </div>
</div>
<script>
    $(function () {
        $(".finished").click(function (e) {
            var oid = $(e.target).attr("id");
            alert(oid);
            var data = {order: {"status": "派工已完工"}};
            $.ajax({
                async: false,
                url: "/orders/" + oid,
                type: "PUT",
                data: data,
                dataType: "json",
                success: function (result) {
                    location.reload();
                }
            })
        });
    });
</script>
</body>
</html>